services:
  api:
    build:
      context: . # Solution directory
      dockerfile: EmployeeScheduleManagementWebApp.Server/Dockerfile
    container_name: employeeschedulemanagementwebappserver-dev
    ports:
      - "8080:8080" # Map HTTP port
      - "8081:8081" # Map HTTPS port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=EmployeeScheduleDb
